# Домашняя работа 01

Настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy.

In [1]:
# Импорт NumPy
import numpy as np

## Создание массивов

In [2]:
# Создание массива из списка
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# Двумерный массив
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
# Массив нулей
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
# Массив единиц
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# Создание последовательности с шагом
np.arange(10, 30, 5)

array([10, 15, 20, 25])

## Атрибуты массивов

In [7]:
# Форма массива
a.shape

(3,)

In [8]:
# Форма двумерного массива
b.shape

(2, 3)

In [9]:
# Тип данных
a.dtype

dtype('int64')

## Индексирование и срезы

In [10]:
# Получение элемента
a[1]

2

In [11]:
# Срез массива
a[1:3]

array([2, 3])

In [12]:
# Извлечение из двумерного массива
b[0:2, 0:3]

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Векторные операции

In [13]:
# Поэлементное сложение
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])
x + y

array([11, 22, 33])

In [14]:
# Поэлементное умножение
x * y

array([10, 40, 90])

## Статистические функции

In [15]:
# Среднее значение
np.mean(x)

20.0

In [16]:
# Сумма элементов
np.sum(x)

60

In [17]:
# Максимальное значение
np.max(x)

30